scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'Node Exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'Influx DB'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8086']

  - job_name: 'Bosch Smarthome Exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080']
