apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: smarthome
    user: user
    url: http://localhost:8086
    jsonData:
      httpMode: GET
    secureJsonData:
      password: password
    editable: false
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://localhost:9090
    editable: false