apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: smarthome
    user: user
    url: http://localhost:8086
    jsonData:
      httpMode: GET
    secureJsonData:
      password: password
  - name: prometheus
    type: Prometheus
    access: direct
    orgId: 1
    url: http://localhost:9090
    editable: false