- name: Install Grafana
  hosts: all
  become: true
  tasks:
    - name: Add Key
      ansible.builtin.apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present
    - name: Add Repo
      ansible.builtin.apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        update_cache: true
    - name: Install
      ansible.builtin.apt:
        name: grafana
        state: latest
    - name: Copy DataSources Provisioning
      ansible.builtin.copy:
        src: resources/grafana/provisioning/datasources.yml
        dest: /etc/grafana/provisioning/datasources/datasources.yml
        owner: root
        group: root
        mode: '0755'

- name: Start Grafana
  hosts: all
  become: true
  tasks:
    - name: Start & Enable Service
      ansible.builtin.service:
        name: grafana-server
        state: started
        enabled: true
