- name: Install InfluxDB
  hosts: all
  become: true
  tasks:
    - name: Import InfluxDB GPG signing key
      apt_key: url=https://repos.influxdata.com/influxdb.key state=present
    - name: Add InfluxDB repository
      apt_repository: repo='deb https://repos.influxdata.com/ubuntu trusty stable' state=present
    - name: Install InfluxDB packages
      apt: name=influxdb state=present
- name: Start InfluxDB
  hosts: all
  become: true
  tasks:
    - name: Modify InfluxDB hostname
      ansible.builtin.replace:
        dest=/etc/influxdb/influxdb.conf
        regexp='hostname = "localhost"'
        replace='hostname = "{{ ansible_hostname }}"'
        backup=yes
    - name: Start the InfluxDB service
      ansible.builtin.service:
        name: influxdb
        state: restarted
        enabled: true

- name: Setup Influx
  tasks:
    - name: Create User
      community.general.influxdb_user:
        user_name: user
        user_password: password
    - name: Create database
      community.general.influxdb_database:
        hostname: "{{localhost}}"
        database_name: "smarthome"
