name: "pre-release"

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ 'amd64', 'arm', 'arm64' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          cache: true
      - name: "Version"
        run: go version
      - name: Build
        run: env GOOS=linux GOARCH=${{matrix.os}} go build -o bosch-smart-home_${{matrix.os}} cmd/main/main.go
      - uses: actions/upload-artifact@v2
        with:
          name: bosch-smart-home_${{matrix.os}}
          path: bosch-smart-home_${{matrix.os}}
  pre-release:
    needs: build
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            bosch-smart-home_amd64/bosch-smart-home_amd64
            bosch-smart-home_arm/bosch-smart-home_arm
            bosch-smart-home_arm64/bosch-smart-home_arm64